### ISSUE TITLE
Page fault when doing `ls` more than 3 times

### ISSUE THREAD

**Issue by ceanvalds** [ceanvalds/ceanos#18]
Doing `ls` more than 3 times page faults.

Edit: now you can do it 5 times
Edit: this will never be fixed

# **Issue**

`kfree()` fails and does not free the memory allocated by `kmalloc()` , resulting in a possible memory leak or another error.

# **Screenshots**

## Page fault

![image](https://github.com/user-attachments/assets/39492329-30d7-478d-a74a-d037f871962a)

## Memseg normally

![image](https://github.com/user-attachments/assets/f5e2a5df-088e-46d3-9bb6-0cae8127c57c)

## Memseg after doing ls 3 times

![image](https://github.com/user-attachments/assets/6140938f-980c-41ac-89f7-757d65438d08)

**Comment by tayoky** [comment]
It crash after 3 times ? Weird because it still have a lot of memory avalibe after 3 times. I think it is something else
