### ISSUE TITLE
pre-built iso?

### ISSUE THREAD

**Issue by webbrowser11** [ceanvalds/ceanos#21]
is there a pre built iso anywhere? that would be easiest for me to run in vmbox.

**Comment by ceanvalds** [comment]
Yes, there is, but because Git is not for uploading binaries, i didn't upload it into the repo. Check out the Releases section, it has a prebuilt iso.

**Comment by webbrowser11** [comment]
ok

**Comment by webbrowser11** [comment]
is releases on the website?

**Comment by ceanvalds** [comment]
Yeah, the website works too

**Comment by webbrowser11** [comment]
> Yeah, the website works too

oh you meant the git hub releases i didn't see one in the latest realease

**Comment by webbrowser11** [comment]
i didnt se one on the website either

**Comment by webbrowser11** [comment]
i dont see one on the site though

**Comment by webbrowser11** [comment]
bruv
